### ISSUE TITLE
XML Parsing Error: no root element found

### ISSUE THREAD

**Issue by ionspicica** [ZeWaren/flask-i18n-example#1]
Hello! such an error in production:
`XML Parsing Error: no root element found
Location: http://cmb.local/static/translations/en/LC_MESSAGES/messages.po
Line Number 1, Column 1: messages.po:1:1
[Show/hide message details.] Error: Error: Gettext 'try_load_lang_po' failed. Unable to exec xmlhttprequest for link [http://cmb.local/static/translations/en/LC_MESSAGES/messages.po]`

**Comment by ZeWaren** [comment]
Are you sure your po file isn't corrupted?
Can you try to open it with another tool and see if it loads?
